import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

const resources = {
  en: {
    translation: {
      // Navigation
      dashboard: "Dashboard",
      orders: "Orders",
      customers: "Customers",
      inventory: "Inventory",
      profitReports: "Profit Reports",
      userManagement: "User Management",
      settings: "Settings",
      logout: "Logout",
      
      // Common
      add: "Add",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      cancel: "Cancel",
      search: "Search",
      filter: "Filter",
      export: "Export",
      print: "Print",
      loading: "Loading...",
      loadingShipmentDetails: "Loading shipment details...",
      noData: "No data available",
      actions: "Actions",
      status: "Status",
      total: "Total",
      confirm: "Confirm",
      
      // Dashboard
      totalRevenue: "Total Revenue",
      totalProfit: "Total Profit",
      totalOrders: "Total Orders",
      totalCustomers: "Total Customers",
      recentOrders: "Recent Orders",
      topCustomers: "Top Customers",
      
      // Orders
      orderNumber: "Order Number",
      customer: "Customer",
      totalAmount: "Total Amount",
      shippingCost: "Shipping Cost",
      commission: "Commission",
      profit: "Profit",
      createdAt: "Created At",
      newOrder: "New Order",
      viewOrder: "View Order",
      editOrder: "Edit Order",
      deleteOrder: "Delete Order",
      orderDetails: "Order Details",
      
      // Order Status
      pending: "Pending",
      processing: "Processing",
      shipped: "Shipped",
      delivered: "Delivered",
      cancelled: "Cancelled",
      
      // Customers
      firstName: "First Name",
      lastName: "Last Name",
      email: "Email",
      phone: "Phone",
      address: "Address",
      city: "City",
      country: "Country",
      postalCode: "Postal Code",
      newCustomer: "New Customer",
      customerDetails: "Customer Details",
      
      // Inventory
      productName: "Product Name",
      sku: "SKU",
      quantity: "Quantity",
      unitPrice: "Unit Price",
      supplier: "Supplier",
      category: "Category",
      inStock: "In Stock",
      outOfStock: "Out of Stock",
      lowStock: "Low Stock",
      newProduct: "New Product",
      
      // Users
      username: "Username",
      password: "Password",
      role: "Role",
      newUser: "New User",
      
      // User Roles
      owner: "Owner",
      customerService: "Customer Service",
      receptionist: "Receptionist",
      sorter: "Sorter",
      stockManager: "Stock Manager",
      
      // Settings
      darkMode: "Dark Mode",
      language: "Language",
      english: "English",
      arabic: "Arabic",
      preferences: "Preferences",
      
      // Invoice
      invoice: "INVOICE",
      invoiceNumber: "Invoice #",
      date: "Date",
      from: "From",
      billTo: "Bill To",
      shipmentDetails: "Shipment Details",
      productDescription: "Product Description",
      qty: "Qty",
      subtotal: "Subtotal",
      shippingHandling: "Shipping & Handling",
      amountInWords: "Amount in Words",
      authorizedBy: "Authorized By",
      receivedBy: "Received By",
      signature: "Signature",
      signatureDate: "Signature & Date",
      thankYou: "Thank you for choosing Lynx!",
      companyTagline: "International Shipping & Purchasing",
      autoGenerated: "This invoice was automatically generated by Lynx Logistics Management System",
      notes: "Notes",
      
      // Forms
      required: "This field is required",
      invalidEmail: "Please enter a valid email address",
      passwordMinLength: "Password must be at least 8 characters",
      
      // Messages
      saveSuccess: "Saved successfully",
      deleteSuccess: "Deleted successfully",
      updateSuccess: "Updated successfully",
      createSuccess: "Created successfully",
      errorOccurred: "An error occurred",
      confirmDelete: "Are you sure you want to delete this item?",
      
      // Auth
      login: "Login",
      loginTitle: "Login to your account",
      loginButton: "Sign In",
      loginSuccess: "Logged in successfully",
      loginError: "Invalid credentials",
      logoutSuccess: "Logged out successfully",
    }
  },
  ar: {
    translation: {
      // Navigation
      dashboard: "لوحة التحكم",
      orders: "الطلبات",
      customers: "العملاء",
      inventory: "المخزون",
      profitReports: "تقارير الأرباح",
      userManagement: "إدارة المستخدمين",
      settings: "الإعدادات",
      logout: "تسجيل الخروج",
      
      // Common
      add: "إضافة",
      edit: "تعديل",
      delete: "حذف",
      save: "حفظ",
      cancel: "إلغاء",
      search: "بحث",
      filter: "تصفية",
      export: "تصدير",
      print: "طباعة",
      loading: "جاري التحميل...",
      loadingShipmentDetails: "جاري تحميل تفاصيل الشحنة...",
      noData: "لا توجد بيانات",
      actions: "إجراءات",
      status: "الحالة",
      total: "الإجمالي",
      confirm: "تأكيد",
      
      // Dashboard
      totalRevenue: "إجمالي الإيرادات",
      totalProfit: "إجمالي الأرباح",
      totalOrders: "إجمالي الطلبات",
      totalCustomers: "إجمالي العملاء",
      recentOrders: "الطلبات الأخيرة",
      topCustomers: "أفضل العملاء",
      
      // Orders
      orderNumber: "رقم الطلب",
      customer: "العميل",
      totalAmount: "المبلغ الإجمالي",
      shippingCost: "تكلفة الشحن",
      commission: "العمولة",
      profit: "الربح",
      createdAt: "تاريخ الإنشاء",
      newOrder: "طلب جديد",
      viewOrder: "عرض الطلب",
      editOrder: "تعديل الطلب",
      deleteOrder: "حذف الطلب",
      orderDetails: "تفاصيل الطلب",
      
      // Order Status
      pending: "قيد الانتظار",
      processing: "قيد المعالجة",
      shipped: "تم الشحن",
      delivered: "تم التسليم",
      cancelled: "ملغي",
      
      // Customers
      firstName: "الاسم الأول",
      lastName: "اسم العائلة",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      address: "العنوان",
      city: "المدينة",
      country: "الدولة",
      postalCode: "الرمز البريدي",
      newCustomer: "عميل جديد",
      customerDetails: "تفاصيل العميل",
      
      // Inventory
      productName: "اسم المنتج",
      sku: "رمز المنتج",
      quantity: "الكمية",
      unitPrice: "سعر الوحدة",
      supplier: "المورد",
      category: "الفئة",
      inStock: "متوفر",
      outOfStock: "غير متوفر",
      lowStock: "مخزون منخفض",
      newProduct: "منتج جديد",
      
      // Users
      username: "اسم المستخدم",
      password: "كلمة المرور",
      role: "الدور",
      newUser: "مستخدم جديد",
      
      // User Roles
      owner: "المالك",
      customerService: "خدمة العملاء",
      receptionist: "موظف الاستقبال",
      sorter: "فارز",
      stockManager: "مدير المخزون",
      
      // Settings
      darkMode: "الوضع الداكن",
      language: "اللغة",
      english: "الإنجليزية",
      arabic: "العربية",
      preferences: "التفضيلات",
      
      // Invoice
      invoice: "فاتورة",
      invoiceNumber: "رقم الفاتورة",
      date: "التاريخ",
      from: "من",
      billTo: "الفاتورة إلى",
      shipmentDetails: "تفاصيل الشحنة",
      productDescription: "وصف المنتج",
      qty: "الكمية",
      subtotal: "المجموع الفرعي",
      shippingHandling: "الشحن والمناولة",
      amountInWords: "المبلغ بالكلمات",
      authorizedBy: "معتمد من",
      receivedBy: "استلم من قبل",
      signature: "التوقيع",
      signatureDate: "التوقيع والتاريخ",
      thankYou: "شكراً لاختياركم Lynx!",
      companyTagline: "للشحن والشراء الدولي",
      autoGenerated: "تم إنشاء هذه الفاتورة تلقائياً بواسطة نظام Lynx لإدارة اللوجستيات",
      notes: "ملاحظات",
      
      // Forms
      required: "هذا الحقل مطلوب",
      invalidEmail: "الرجاء إدخال بريد إلكتروني صالح",
      passwordMinLength: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
      
      // Messages
      saveSuccess: "تم الحفظ بنجاح",
      deleteSuccess: "تم الحذف بنجاح",
      updateSuccess: "تم التحديث بنجاح",
      createSuccess: "تم الإنشاء بنجاح",
      errorOccurred: "حدث خطأ",
      confirmDelete: "هل أنت متأكد من حذف هذا العنصر؟",
      
      // Auth
      login: "تسجيل الدخول",
      loginTitle: "تسجيل الدخول إلى حسابك",
      loginButton: "تسجيل الدخول",
      loginSuccess: "تم تسجيل الدخول بنجاح",
      loginError: "بيانات الاعتماد غير صالحة",
      logoutSuccess: "تم تسجيل الخروج بنجاح",
    }
  }
};

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: false,
    interpolation: {
      escapeValue: false,
    },
    detection: {
      order: ['localStorage', 'navigator'],
      caches: ['localStorage'],
    }
  });

export default i18n;
