services:
  - type: web
    name: tajway-logistics
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DARB_ASSABIL_API_TOKEN
        sync: false
      - key: DARB_ASSABIL_USERNAME
        sync: false
